name: Discord push notifications

on:
  push:

permissions: {}

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline Pling
        uses: Qbox-project/pipeline-pling@v1.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          accent-color: "6ed0f3"