name: Discord push notifications

on:
  release:
    types: [published]

jobs:
  notify-discord:
    name: Discord Releases Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Github Releases To Discord
      uses: SethCohen/github-releases-to-discord@v1.16.2
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        accent-color: "6ed0f3"
        username: ${{ github.event.repository.name }}
        footer_timestamp: true
        fields:
          - name: Version
            value: ${{ github.event.release.tag_name }}
          - name: Author
            value: ${{ github.event.release.author.login }}
          - name: Changes
            value: ${{ github.event.release.body }}